import "@mantine/core/styles.css"
import { Inter } from "next/font/google"
import { BlitzProvider } from "./blitz-client"

import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from "@mantine/core"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: { title: "New Blitz App", template: "%s – Blitz" },
  description: "Generated by blitz new ",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider defaultColorScheme="dark">
          <BlitzProvider>
            <>{children}</>
          </BlitzProvider>
        </MantineProvider>
      </body>
    </html>
  )
}
