import {
  AppShell,
  AppShellFooter,
  AppShellHeader,
  AppShellMain,
  ColorSchemeScript,
  Group,
  mantineHtmlProps,
  MantineProvider,
  Text,
} from "@mantine/core"
import "@mantine/core/styles.css"
import { Inter } from "next/font/google"
import { BlitzProvider } from "./blitz-client"

const inter = Inter({ subsets: ["latin"] })
export const metadata = {
  title: { title: "New Blitz App", template: "%s – Blitz" },
  description: "Generated by blitz new ",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body className={inter.className}>
        <MantineProvider defaultColorScheme="dark">
          <AppShell header={{ height: 60 }} footer={{ height: 60 }} padding="md">
            <BlitzProvider>
              <AppShellHeader>
                <Group h="100%" px="md">
                  <Text size="lg" fw={500}>
                    Eventio
                  </Text>
                </Group>
              </AppShellHeader>

              <AppShellMain>{children}</AppShellMain>

              <AppShellFooter>
                <Group justify="center" h="100%">
                  <Text size="sm">© 2025 Your App. All rights reserved.</Text>
                </Group>
              </AppShellFooter>
            </BlitzProvider>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  )
}
